### ISSUE TITLE
paket dizininde eski pisiler mevcut ise ilker deposundan indirmiyor

### ISSUE THREAD

**Issue by ertugerata** [ilkermanap/pisi-chroot-build#14]
pisi up da mevcut olan
   -s [--compare-sha1sum]      : compare sha1sum repo and installed packages

benzeri bir makenizma ile CACHE paket dizini içinde olan paketin depolarda mevcut olan en güncel olup olmadığı kontroledilmeli.

**Comment by ilkermanap** [comment]
Paket isimlerine karsilik gelen tam dosya adi, repo pisi-index.xml dosyasindan aliniyor. Dosya adi degismis ise, yeniden cekilmesi gerekiyor. Paket nesnesi, pisi-index.xml icinde bulunan dosya adinin varligini kontrol ediyor. Bu durumda, guncellemelerde dosya adlarinin degisip degismedigini sormam gerekiyor.

**Comment by ertugerata** [comment]
dosya adı ile değil paket sha1sum ile kontrol etmemiz lazım diye düşünüyorum

**Comment by ertugerata** [comment]
bu hallolmuş idi. kapanabilir
